# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visivel', models.BooleanField(default=True, verbose_name='Visibilidade')),
                ('institucional', models.BooleanField(default=True, verbose_name='Institucional')),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100, verbose_name='nome do Evento')),
                ('dataEHoraDeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hora e data Inicio')),
                ('dataEHoraDeFim', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hora e data Fim')),
                ('onde', models.CharField(max_length=200, verbose_name='endereco')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipoAgenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.TipoAgenda'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
