# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='compartilhar',
            field=models.BooleanField(default=True, verbose_name='Compartilhar'),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
